export const GET_ALL_ANALYTICS_USER_REQUEST = "GET_ALL_ANALYTICS_USER_REQUEST";
export const GET_ALL_ANALYTICS_USER_REQUEST_SUCCESS =
  "GET_ALL_ANALYTICS_USER_REQUEST_SUCCESS";
export const GET_ALL_ANALYTICS_USER_REQUEST_FAILED =
  "GET_ALL_ANALYTICS_USER_REQUEST_FAILED";

export const ADD_ANALYTICS_REQUEST = "ADD_ANALYTICS_REQUEST";
export const ADD_ANALYTICS_REQUEST_SUCCESS = "ADD_ANALYTICS_REQUEST_SUCCESS";
export const ADD_ANALYTICS_REQUEST_FAILED = "ADD_ANALYTICS_REQUEST_FAILED";
