export const GET_ALL_ANALYTICS_USER_REQUEST = "GET_ALL_ANALYTICS_USER_REQUEST";
export const GET_ALL_ANALYTICS_USER_REQUEST_SUCCESS =
  "GET_ALL_ANALYTICS_USER_REQUEST_SUCCESS";
export const GET_ALL_ANALYTICS_USER_REQUEST_FAILED =
  "GET_ALL_ANALYTICS_USER_REQUEST_FAILED";

export const ADD_ANALYTICS_REQUEST = "ADD_ANALYTICS_REQUEST";
export const ADD_ANALYTICS_REQUEST_SUCCESS = "ADD_ANALYTICS_REQUEST_SUCCESS";
export const ADD_ANALYTICS_REQUEST_FAILED = "ADD_ANALYTICS_REQUEST_FAILED";

export const GET_ALL_ANALYTIC_WEB_REQUEST = "GET_ALL_ANALYTIC_WEB_REQUEST";
export const GET_ALL_ANALYTIC_WEB_REQUEST_SUCCESS =
  "GET_ALL_ANALYTIC_WEB_REQUEST_SUCCESS";
export const GET_ALL_ANALYTIC_WEB_REQUEST_FAILED =
  "GET_ALL_ANALYTIC_WEB_REQUEST_FAILED";

export const GET_WEB_REVENUE_REQUEST = "GET_WEB_REVENUE_REQUEST";
export const GET_WEB_REVENUE_REQUEST_SUCCESS =
  "GET_WEB_REVENUE_REQUEST_SUCCESS";
export const GET_WEB_REVENUE_REQUEST_FAILED = "GET_WEB_REVENUE_REQUEST_FAILED";

export const GET_COMPANY_REVENUE_REQUEST = "GET_COMPANY_REVENUE_REQUEST";
export const GET_COMPANY_REVENUE_REQUEST_SUCCESS =
  "GET_COMPANY_REVENUE_REQUEST_SUCCESS";
export const GET_COMPANY_REVENUE_REQUEST_FAILED =
  "GET_COMPANY_REVENUE_REQUEST_FAILED";
