export const GET_ALLUSERS_REQUEST = "GET_ALLUSERS_REQUEST";
export const GET_ALLUSERS_REQUEST_SUCCESS = "GET_ALLUSERS_REQUEST_SUCCESS";
export const GET_ALLUSERS_REQUEST_FAILED = "GET_ALLUSERS_REQUEST_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_REQUEST_SUCCESS = "UPDATE_USER_REQUEST_SUCCESS";
export const UPDATE_USER_REQUEST_FAILED = "UPDATE_USER_REQUEST_FAILED";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_REQUEST_SUCCESS = "DELETE_USER_REQUEST_SUCCESS";
export const DELETE_USER_REQUEST_FAILED = "DELETE_USER_REQUEST_FAILED";

export const FILTER_ACTIVE_USERS = "FILTER_ACTIVE_USERS";
export const FILTER_ACTIVE_USERS_SUCCESS = "FILTER_ACTIVE_USERS_SUCCESS";

export const FILTER_INACTIVE_USERS = "FILTER_INACTIVE_USERS";
export const FILTER_INACTIVE_USERS_SUCCESS = "FILTER_INACTIVE_USERS_SUCCESS";
