export const GET_ALLUSERS_REQUEST = "GET_ALLUSERS_REQUEST";
export const GET_ALLUSERS_REQUEST_SUCCESS = "GET_ALLUSERS_REQUEST_SUCCESS";
export const GET_ALLUSERS_REQUEST_FAILED = "GET_ALLUSERS_REQUEST_FAILED";
